### ISSUE TITLE
[Improvements] We can improve website 

### ISSUE THREAD

**Issue by fynks** [icon-blender/icon-blender#1]
Hello there,i just saw your project by seeing your post on reddit and noticed that we can improve a couple of things in project website itself.I'm attaching a detailed report of Lighthouse test that i did.
By the way i just loved your project and this idea of yours.
- If you need my help in optimizing the website performance,just contact me on this issue.
[icon-blender.pdf](https://github.com/icon-blender/icon-blender/files/6371330/icon-blender.pdf)

**Comment by oyejorge** [comment]
That's a little frustrating. When I ran the check it gave me 98% for mobile performance. Definitely still some things to improve on though. Thanks!

**Comment by oyejorge** [comment]
Alright, looking a lot better now. Here's what I'm getting:

![Screenshot from 2021-04-25 13-53-32](https://user-images.githubusercontent.com/1043524/116007599-bd6f5180-a5cd-11eb-8c7f-2028618cdf40.png)

**Comment by fynks** [comment]
Yes it is much better now,thanks for this awesome project
